apiVersion: v1
kind: Secret
metadata:
  name: jobqueue-credentials
type: Opaque
stringData:
  POSTGRES_USER: jobqueue
  POSTGRES_PASSWORD: jobqueue
  POSTGRES_DB: jobqueue
  RABBITMQ_DEFAULT_USER: jobqueue
  RABBITMQ_DEFAULT_PASS: jobqueue
  DATABASE_URL: postgres://jobqueue:jobqueue@postgres:5432/jobqueue?sslmode=disable
  AMQP_URL: amqp://jobqueue:jobqueue@rabbitmq.default.svc.cluster.local:5672/
  RABBITMQ_MANAGEMENT_URL: http://jobqueue:jobqueue@rabbitmq.default.svc.cluster.local:15672
