apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: distributedjobqueue-worker
        image: distributedjobqueue-worker
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DATABASE_URL
          value: postgres://jobqueue:jobqueue@postgres:5432/jobqueue?sslmode=disable
        - name: AMQP_URL
          value: amqp://jobqueue:jobqueue@rabbitmq:5672/

